#!/usr/bin/python
# -*- coding: utf-8 -*-

import os
import time


def menu():
    os.system('clear')
    print
    print("")
    print("--------------------------------")
    print("         MENU INSTALACION       ")
    print("--------------------------------")
    print("")
    print("     Selecciona una opcion:")
    print("\t1 - Actualizar sistema")
    print("\t2 - Instalacion AUTOMATICA LCD (Se Reiniciará)")
    print("\t3 - Instalador LCD (Sin reinicio)")
    print("\t4 - Instalador Driver LCD (Sin reinicio)")
    print("\t5 - Cambiar de LCD a HDMI")
    print("\t6 - Cambiar de HDMI a LCD")
    print("\t7 - Instalar TouchUI (Automatico)")
    print("\t8 - Reinstalar TouchUI <<<EN CONSTRUCCION>>>")
    print("\t9 - Instalar OctoDash")
    print("\t10 - Actualizar OctoDash")
    print("\t11 - Reiniciar")
    print("\t0 - Salir")
    print("")


while True:
    menu()
    opcionMenu = input("    Inserte el numero de la opcion: ")

    if opcionMenu == 1 :
        print("")
        print("ACTUALIAZACION DEL SISTEMA")
        os.system('sudo apt-get update -y')
        time.sleep(3)
        os.system('sudo apt-get upgrade -y')
        time.sleep(3)
        print("")
        print("...actualizacion completada...")
        print("Pulsa ENTER para continuar...")
        input()
        time.sleep(5)

    elif opcionMenu ==  2 :
        print("")   
        print("INSTALACION AUTOMATICA LCD")
        print(" ---> Se Reiniciará <---  ")
        print(""
        "")
        os.system('cd ~')
        time.sleep(3)
        print("Bajando archivos...")
        os.system('wget http://kedei.net/IMG/v6_1/LCD_show_v6_1_3.tar.gz')
        time.sleep(3)
        print("...Descomprimiendo archivos...")
        os.system('tar xzvf LCD_show_v6_1_3.tar.gz')
        time.sleep(3)
        print("...abriendo carpeta...")
        os.system('cd LCD_show_v6_1_3')
        time.sleep(3)
        print("...ejecutando LCD_show_v6_1_3")
        os.system('./LCD35_v')
        time.sleep(5)
        print("Empezamos con el Driver")
        print("...bajando driver...")
        os.system('cd ~')
        os.system('wget https://sourceforge.net/projects/wavetech/files/lcd.tar.gz')
        time.sleep(3)
        print("...descomprimiendo...")
        os.system('tar -xf lcd.tar.gz')
        time.sleep(3)
        print("")
        print("+--------------------------------------+")
        print("|          INSTALANDO LOS DRIVER       |")
        print("+--------------------------------------+")
        print("")
        time.sleep(5)
        print("...actualizando Kernel...")
        os.system('sudo cp ./lcd_files/kernel.img /boot/kernel.img')
        os.system('sudo cp ./lcd_files/kernel7.img /boot/')
        os.system('sudo cp ./lcd_files/*.dtb /boot/')
        os.system('sudo cp ./lcd_files/overlays/*.dtb* /boot/overlays/')
        time.sleep(3)
        print("...subiendo modulos kernel...")
        os.system('sudo cp -rf ./lcd_files/lib/* /lib/')
        os.system('sudo rm /boot/bcm2710-rpi-3-b-plus.dtb')
        time.sleep(3)
        print("...desabilitando actualizacion del kernel...")
        os.system('sudo apt-mark hold raspberrypi-kernel')
        print("--> INSTALACION COMPLETADA <--")
        time.sleep(3)
        print("...REINICIANDO...")
        time.sleep(5)
        os.system('sudo reboot')

    elif opcionMenu ==  3 :
        print("")
        print("   INSTALACION LCD    ")
        print("---> Sin reinicio <---")
        print("")
        time.sleep(3)
        print("Bajando archivos...")
        os.system('cd~')
        os.system('wget http://kedei.net/IMG/v6_1/LCD_show_v6_1_3.tar.gz')
        time.sleep(3)
        print("...Descomprimiendo archivos...")
        os.system('tar xzvf LCD_show_v6_1_3.tar.gz')
        time.sleep(3)
        print("...abriendo carpeta...")
        os.system('cd LCD_show_v6_1_3')
        time.sleep(3)
        print("...ejecutando LCD_show_v6_1_3")
        os.system('LCD_show_v6_1_3/./LCD35_v')
        time.sleep(3)
        print("--> INSTALACION COMPLETADA <---")
        print("Se debe reiniciar para que los cambios tengan efectos.")
        print("Pulsa ENTER para continuar...")
        input()

    elif opcionMenu ==  4 :
        print("")
        print("   INSTALACION DRIVE    ")
        print("---> Sin reinicio <---  ")
        print("")
        time.sleep(3)
        print("...actualizando Kernel...")
        os.system('sudo cp ./lcd_files/kernel.img /boot/kernel.img')
        os.system('sudo cp ./lcd_files/kernel7.img /boot/')
        os.system('sudo cp ./lcd_files/*.dtb /boot/')
        os.system('sudo cp ./lcd_files/overlays/*.dtb* /boot/overlays/')
        time.sleep(3)
        print("...subiendo modulos kernel...")
        os.system('sudo cp -rf ./lcd_files/lib/* /lib/')
        os.system('sudo rm /boot/bcm2710-rpi-3-b-plus.dtb')
        time.sleep(3)
        print("...desabilitando actualizacion del kernel...")
        os.system('sudo apt-mark hold raspberrypi-kernel')
        time.sleep(3)
        print("--> INSTALACION COMPLETADA <--")
        print("PARA QUE LOS CAMBIOS TENGAN EFECTOS, SE DEBE REINICIAR")
        input()

    elif opcionMenu ==  5 :
        print("")
        print(" DE LCD A HDMI")
        print("Se debe reiniciar para que los cambios surtan efectos")
        print("")
        time.sleep(3)
        print("...abriendo carpeta...")
        os.system('cd ~')
        os.system('cd LCD_show_v6_1_3')
        time.sleep(3)
        print("...ejecutando LCD_show_v6_1_3")
        os.system('./LCD_dhmi')
        time.sleep(3)
        print("--> INSTALACION COMPLETADA <--")
        print("Pulsa ENTER para continuar...")
        input()

    elif opcionMenu == 6 :
        print("")
        print(" DE HDMI A LCD")
        print("Se debe reiniciar para que los cambios surtan efectos.")
        print("")
        time.sleep(3)
        print("...abriendo carpeta LCD_show_v6_1_3...")
        os.system('cd ~')
        os.system('cd LCD_show_v6_1_3')
        time.sleep(3)
        os.system('./LCD35_v')
        print("--> INSTALACION COMPLETADA <--")
        print("Pulsa ENTER para continuar...")
        input()

    elif opcionMenu ==  7 :
        print("")
        print(" INSTALACION DEL TOUCHUI ")
        print("Se debe continuar para que los cambios surtan efectos...")
        os.system('cd ~')
        os.system('git clone https://github.com/BillyBlaze/OctoPrint-TouchUI-autostart.git ~/TouchUI-autostart/')
        os.system('sudo ~/TouchUI-autostart/helpers/install')
        print("--> INSTALACION COMPLETADA <--")
        print("Pulsa ENTER para continuar...")
        input()

    elif opcionMenu ==  8 :
        print("")
        print(" EN PROCESO DE CONSTRUCCION ")
        #print("--> INSTALACION COMPLETADA <--")

    elif opcionMenu == 9 :
        print("")
        print(" INSTALACION DE OCTODASH")
        print("Se debe continuar para que los cambios surtan efectos.")
        print("")
        os.system('cd ~')
        os.system('bash <(wget -qO- https://github.com/UnchartedBull/OctoDash/raw/master/scripts/install.sh)')
        time.sleep(3)
        print("--> INSTALACION COMPLETADA <--")
        print("Pulsa ENTER para continuar...")
        input()

    elif opcionMenu == 10 :
        print("")
        print(" ACTUALIAZACION DE OCTODASH")
        print("Se debe continuar para que los cambios surtan efectos.")
        print("")
        os.system('cd ~')
        os.system('wget -qO- https://github.com/UnchartedBull/OctoDash/raw/master/scripts/update.sh | bash')
        time.sleep(3)
        print("--> INSTALACION COMPLETADA <--")
        print("Pulsa ENTER para continuar...")
        input()        

    elif opcionMenu ==  11 :
        print("REINICIANDO")
        time.sleep(5)
        os.system('sudo reboot')

    elif opcionMenu ==  0 :
        break

    else:
        input("No has elegido ninguna opcion...ESPABILAO!!")
